name = "Developer Portfolio"
license = "MIT"
 #licenselink = "https://github.com/samrobbins85/hugo-developer-portfolio/blob/master/LICENSE"
description = "A Portfolio website designed for developers"

tags = ["portfolio", "developer", "responsive","uikit"]
features = ["uikit", "responsive", "features"]
min_version = "0.54.0"

[author]
    name = "Sakeel jawfer"
    homepage = "/Home"

